# Generated by Django 3.0.3 on 2020-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
