# Generated by Django 3.0.3 on 2020-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_link_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='product_name',
            field=models.CharField(default='', editable=False, max_length=10000),
        ),
        migrations.AddField(
            model_name='link',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='review',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default=None, max_length=10000),
            preserve_default=False,
        ),
    ]
