# Generated by Django 3.0.3 on 2020-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200329_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='product_name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='link',
            name='rating',
            field=models.FloatField(),
        ),
    ]
