# Generated by Django 3.0.3 on 2020-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200329_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=10)),
            ],
        ),
    ]
