# Generated by Django 3.0.3 on 2020-04-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_calcu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calcu',
        ),
    ]
