# Generated by Django 3.0.3 on 2020-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_delete_calcu'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='path',
            field=models.CharField(default='something', max_length=10000),
            preserve_default=False,
        ),
    ]
